### ISSUE TITLE
Display user profile picture in navigation bar

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#103]
The navigation bar should display the user's profile page on dropdown.

- Refer to [details.component.html](https://github.com/Cynthesize/cynthesize-frontend/blob/master/src/app/profile/user/details/details.component.html#L10) for use of profile picture. Currently we're also storing the user image link in the local storage. You should fetch the link/public id of the image and use that.

Refer to the screenshot for placement of image.
![screenshot from 2019-02-11 18-49-19](https://user-images.githubusercontent.com/45864807/52565789-dc8aca00-2e2d-11e9-8c7a-cc34fb51fc52.png)

**Comment by prijeshb** [comment]
working on it

**Comment by PrathamDogra** [comment]
Working on it.

**Comment by prijeshb** [comment]
Is this good or should change something?
![screenshot 167](https://user-images.githubusercontent.com/16492616/52690023-50d68200-2f82-11e9-87a0-6fd4033d7e18.png)

**Comment by prijeshb** [comment]
Is this Good or should I change anything ? 

![screenshot 167 1](https://user-images.githubusercontent.com/16492616/52690174-ccd0ca00-2f82-11e9-848d-de053a4469a3.png)

**Comment by WickedBrat** [comment]
Hey! Please float the image to the right side. That way it leaves lesser
whitespace.

**Comment by prijeshb** [comment]
how about this ?

![screenshot 170 1](https://user-images.githubusercontent.com/16492616/52704086-cc95f600-2fa5-11e9-9876-5df9a97bcdbe.png)
