### ISSUE TITLE
Set minimum character limit to ideas and project description 

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#107]
Do not allow submitting the idea or project if the description is less than fixed number of letters.

- [ ] **For projects:** Limit should be 150 characters.
- [ ] **For ideas:** Limit should be 50 characters.

**Comment by sanyamdogra** [comment]
Claim ?

**Comment by WickedBrat** [comment]
@sanyamdogra you may go forward with this.
