### ISSUE TITLE
Make project dashboard page responsive

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#108]
This is a big feature so kindly discuss your implementation before starting to work on this issue.

**Comment by PrathamDogra** [comment]
So here is what I thought. First we need to install bootstrap (using npm install bootstrap) and then use the grid system of bootstrap in the required html file.

**Comment by WickedBrat** [comment]
@PrathamDogra In our project, we already use Angular Material 2. Using Angular Material 2 with Bootstrap would make the dependencies very heavy and reduce the response time of the site making it bloaty. 

I'd suggest going with the flex layout for the issues.

**Comment by PrathamDogra** [comment]
Okay will try it with flex layout.

**Comment by zerefwayne** [comment]
@PrathamDogra The layout is designed purely with scss and flexbox.
