### ISSUE TITLE
Text is cut-off from bottom in edit fields on profile page

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#109]
**To Reproduce**  

1. Go to profile page
2. Click on edit icon
3. Type something in any input field, characters with lower serif get cut off.

**Screenshots**  

![image](https://user-images.githubusercontent.com/28949397/52644001-175f3180-2f04-11e9-82cf-890f71749504.png)

**Comment by PrathamDogra** [comment]
Working on this,

**Comment by PrathamDogra** [comment]
@zerefwayne the issue is being resolved
![untitled](https://user-images.githubusercontent.com/43649218/52704894-a1aca180-2fa7-11e9-8ca3-ccc0aea02146.png)
