### ISSUE TITLE
Idea card on profile page extends beyond 50%

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#110]
**Describe the bug**
The idea card has a property `flex: 0 0 49%` defined but it extends beyond it when text is too long.

**To Reproduce**

1. Add a new idea with similar text as this.
2. Go to profile page

**Expected Behaviour**

2 cards should be lined up in a row always.

**Screenshots**

![image](https://user-images.githubusercontent.com/28949397/52644274-88064e00-2f04-11e9-82e6-95d81421aa14.png)

**Comment by WickedBrat** [comment]
@zerefwayne, I don't think we'll ever come across this issue. The
description would never have any such text in it.
