### ISSUE TITLE
Use Project name as well in the URL

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#112]
Currently any project can be viewed as `/view/project/<project-id>`. This should not be the case. The project name should be `/view/project/<project-id>-<project-name>`.

Eg: The URL for the Cynthesize project is currently `/view/project/191`, it should be `/view/project/191-Cynthesize`.

This needs to be completed in two parts: 

- [x] Modifying query to match for project name as well.

- [x] Modifying API call.

**Comment by Jaggu-123** [comment]
@WickedBrat claim
