### ISSUE TITLE
Bug in small screen idea feed navigation

### ISSUE THREAD

**Issue by prijeshb** [Cynthesize/cynthesize-frontend#118]
**Describe the bug**
On small screen by clicking on Idea feed navigates to home.

**Expected behavior**
On clicking Idea feed should navigate to Ideas page

**Screenshots**

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/16492616/52731674-4ea50f80-2fe4-11e9-83f8-e967ee63d3cf.gif)
 .

**Comment by WickedBrat** [comment]
@prijeshb Would you like to take this?

**Comment by Jaggu-123** [comment]
@WickedBrat I would like to take this issue

**Comment by prijeshb** [comment]
@Jaggu-123 sorry but already made PR for this.
