### ISSUE TITLE
Change URL for checkpoints

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#120]
**Steps to reproduce:**
- Open any projects page.
- Open/Add any checkpoint from the left navbar.
- Notice that the route doesn't change

**Expected Behaviour:**
The URL for different checkpoints should change. For example: when we open "Design" checkpoint (say), The URL should something like `/view/project/191-Cynthesize/Design`. 

**Current Behaviour:**
The URL remains the same `/view/project/191-Cynthesize`

**Help for solving the issue:**
You may see [this video](https://www.youtube.com/watch?v=QC6wRxXT26I&list=PLC3y8-rFHvwhBRAgFinJR8KHIrCdTkZcZ&index=25&t=0s) for better understanding of Angular routing and solving this issue.

**Comment by sanyamdogra** [comment]
I am giving it a shot @WickedBrat

**Comment by sanyamdogra** [comment]
@WickedBrat please close this too
