### ISSUE TITLE
Add Idea page is not responsive

### ISSUE THREAD

**Issue by richa208** [Cynthesize/cynthesize-frontend#121]
**Describe the bug**
On resizing the window, add idea page does not resize and the scroll bar also doesn't allows to view the entire modal.

**Expected behavior**
On changing the screen size the page should resize accordingly to aid users.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25206394/52770122-4b4b6b80-3058-11e9-9764-602ea1f6499d.gif)

**Comment by WickedBrat** [comment]
@richa208 Thanks for raising the PR! Would you like to take this?

**Comment by richa208** [comment]
Yes sure
