### ISSUE TITLE
Profile picture not being shown in user page mobile view.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#128]
**Screenshots**  

#### Desktop View
![image](https://user-images.githubusercontent.com/28949397/52810686-22a78e00-30b9-11e9-912a-23c406a77aa2.png)

### Mobile View
![image](https://user-images.githubusercontent.com/28949397/52810730-3ce16c00-30b9-11e9-8a9f-22c2f6b9bfdc.png)

**Comment by revanth-reddy** [comment]
@zerefwayne can I work on this? Please assign me.

**Comment by prijeshb** [comment]
@revanth-reddy You  already have claimed an issue. If you are not working on it unclaim it.

**Comment by AdityaAnandKrishna** [comment]
Can I work on this issue ?

**Comment by AdityaAnandKrishna** [comment]
![cynthesize 7](https://user-images.githubusercontent.com/33352601/52902483-3e38a300-3237-11e9-9c46-f79d23f03da1.png)
Is it ok

**Comment by WickedBrat** [comment]
Looks good to me @zerefwayne
