### ISSUE TITLE
Issue with profile picture in header dropdown.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#130]
**Describe the bug**
When someone opens the website for the first time, the design looks okay. But as soon as we navigate to some other page, the alignment breaks.

**To Reproduce**
1. Make a hard refresh on the website. Click the menu on header.
2. Click on **Profile** option.
3. Click on the menu again.

**Screenshots**

**Expected view**
![image](https://user-images.githubusercontent.com/28949397/52810992-00fad680-30ba-11e9-8c49-6dbafdf598ad.png)

**After clicking on any other page**
![image](https://user-images.githubusercontent.com/28949397/52811092-41f2eb00-30ba-11e9-9c57-e7c37fe466ab.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Would you like to work on this issue?**
No

**Comment by WickedBrat** [comment]
@prijeshb in continuation with your PR #122. PTAL

**Comment by revanth-reddy** [comment]
@prijeshb Can I work on this issue?

**Comment by prijeshb** [comment]
@revanth-reddy NO
You can checkout other issues :)
