### ISSUE TITLE
User details in idea card depends on length of username. 

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#131]
**Describe the bug**

The div's width depends on the length of the username despite it having a fix width defined.

**Screenshots**

![image](https://user-images.githubusercontent.com/28949397/52811829-18d35a00-30bc-11e9-8e10-a48268561e66.png)

**Would you like to work on this issue?**
No

**Comment by Jaggu-123** [comment]
@zerefwayne I will take this issue

**Comment by zerefwayne** [comment]
@Jaggu-123 You've two issues already assigned. Unclaim them if you're not working on them.

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne Can I work on this issue. 
will you assign this issue to me ?

**Comment by zerefwayne** [comment]
@AdityaAnandKrishna Yes you can work on this issue.

**Comment by AdityaAnandKrishna** [comment]
![cynthesize 1](https://user-images.githubusercontent.com/33352601/52896980-be89e480-31f4-11e9-85e6-8d65e7295c5a.png)

Is it ok

**Comment by WickedBrat** [comment]
LGTM
