### ISSUE TITLE
Add loader at appropriate places

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#14]
We need material spinners at different places around the site. For eg: when a component is being loaded or a service is being waited for.

Add the following code to add spinner:
`<div class="loader" *ngIf="!isPageLoaded"><mat-spinner></mat-spinner></div>`
and declare the variable `isPageLoaded=false` in the respective `component.ts` file. This variable will be changed to `true` once the response is complete.

Look at the file [details.component.ts](https://github.com/Cynthesize/frontend/blob/master/src/app/profile/user/details/details.component.ts) and [details.component.html](https://github.com/Cynthesize/frontend/blob/master/src/app/profile/user/details/details.component.html) for an example.

**Comment by thesmallstar** [comment]
@opencodebot claim

**Comment by zerefwayne** [comment]
@thesmallstar You can work on this :+1:

**Comment by thesmallstar** [comment]
@zerefwayne  Are there any specific places I need to put it on? Or I need to put it in every possible component?

**Comment by WickedBrat1** [comment]
You need to put this wherever API calls are made via the apollo client and the returning data is used to create html. You may find places where HTML content is rendered upon checking an if condition. Eg: `*ngIf="comments"`

**Comment by thesmallstar** [comment]
@WickedBrat1 I was a little confused while doing this. For now I am unclaiming the issue. I will take it as I am more familiar with the project :)

**Comment by neozenweb** [comment]
Can I take a stab at this one? I think with the info from the messages above, I may be able to work on this issue. Thanks

**Comment by WickedBrat** [comment]
Go ahead with this @neozenweb

**Comment by neozenweb** [comment]
02/12 update: 
src->app->add->add-idea   Variable isLoaded (done)
src->app->add->project        variable formNotfilled (done)
src->app->profile->user->details(the example given in the earlier messages)   variable isPageLoaded  (already completed)
Questions:
1. I have tested these changes in the testing environment where there is not much data so the spinner is not even showing. How do I test under delaying data situations?? Can you please give me /point to the steps as I am a new member.
2. I think this fix needs to be recurring as the development progresses, am I correct?

**Comment by neozenweb** [comment]
I have added the spinner loader for 4 components(html and ts):

src/app/add/add-idea components
src/app/add/project components
src/app/shared/comments  components
src/app/shared/liking components

I have tested the changes using setTimeout(). What are my next steps? Should I do a pull request? 
Can you point out to me to any standard procedure for the pull request, merge etc. Thanks.

**Comment by WickedBrat** [comment]
@neozenweb You may start create a PR with appropriate title and referencing this issue with text `Fixes #14` in the PR description
