### ISSUE TITLE
Excess padding in view idea modal.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#140]
**To Reproduce**
1. Open idea feed page.
2. Click on expand button on any idea.

**Expected behavior**
The excess padding should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/28949397/52913881-135a5780-32e8-11e9-854a-5c8bd6f98209.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 72

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne  you are talking about mat-dialog box padding or idea container

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne  I think decreasing the padding by 1 rem for both mat-dialog and container-idea will be ok

**Comment by zerefwayne** [comment]
@AdityaAnandKrishna Yeah it is related to mat-dialog box. Try removing the default padding.

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne  so you want me to remove  or decrease the mat-dialog padding.
for me if I remove the padding then it looks much better and i can add some box- shadow to the container-idea

**Comment by prijeshb** [comment]
@AdityaAnandKrishna I think so removing fixes it

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne   we cant simply change the property of mat-dialog-container
I tried to override the property of mat-dialog-container but it did't worked i.e
--> add css in idea-feed.component.scss
      .custom-dialog-container.mat-dialog-container { 
        padding: 0 !important;
      }
--> add  panelClass: 'custom-dialog-container' in openDialog functon   of idea-feed.component.ts

      const dialogRef = this.dialog.open(IdeaCardComponent, {
          panelClass: 'custom-dialog-container', 
          width: 'auto',
          data: { idea }
      });
