### ISSUE TITLE
Number of ideas on one page in Idea Feed doesn't work properly.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#141]
**Describe the bug**
When we change number of ideas form 5 to 10, it doesn't work as expected.

**To Reproduce**
1. Go to Idea Feed
2. Change the number of ideas from 5 to 10
3. See error

**Expected behavior**
Set the default number of ideas as 10 and remove the facility to change number of ideas.

**Screenshots**
![cynthesize issue 1](https://user-images.githubusercontent.com/28949397/52913954-ebb7bf00-32e8-11e9-91e6-f475e8b4fe48.gif)

**Comment by thesmallstar** [comment]
Can I work on this?

**Comment by WickedBrat** [comment]
@thesmallstar I had a little bit different idea for implementing `virtual scroll` on this, page. I've assigned it to you. :+1:
