### ISSUE TITLE
Bug in edit profile view.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#142]
**Describe the bug**
Serifs are being cutoff from bottom in edit profile view.

**To Reproduce**
1. Go to Profile
2. Click on Edit Button
3. Type some characters 'y', 'g', 'p' with lower serifs in input fields.

**Expected behavior**
Their should be proper padding so that serifs don't get cut off.

**Screenshots**
![image](https://user-images.githubusercontent.com/28949397/52914413-d42f0500-32ed-11e9-938f-53e25c0ba815.png)

**Comment by Jaggu-123** [comment]
@zerefwayne I will work on it

**Comment by prijeshb** [comment]
@zerefwayne @Jaggu-123  This issue is already listed and I guess resolved #109
