### ISSUE TITLE
Redirection while editing profile

### ISSUE THREAD

**Issue by richa208** [Cynthesize/cynthesize-frontend#145]
**Describe the bug**
Redirection to Add Projects page while editing the profile.

**To Reproduce**
1. Go to 'Profile'
2. While editing location, birthday or bio if we press Enter then redirection to Add Projects page occurs.

**Expected behavior**
No redirection and save feature instead.

**Screenshots**

![edut](https://user-images.githubusercontent.com/25206394/52929230-8ce65a00-3369-11e9-81be-1a5850e9370d.gif)

**Comment by prijeshb** [comment]
@richa208 would you like to take this ?

**Comment by zerefwayne** [comment]
@richa208 Assigned to you.

**Comment by richa208** [comment]
@prijeshb if you want, you can take up this issue.
@zerefwayne if it is ok...
