### ISSUE TITLE
No save button after editing profile 

### ISSUE THREAD

**Issue by richa208** [Cynthesize/cynthesize-frontend#152]
**Describe the bug**
After editing the profile there is no button to save the changes.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'edit'
3. Make any changes

**Expected behavior**
After making any change, user should have the option to cancel or save it.

**Screenshots**
![edit](https://user-images.githubusercontent.com/25206394/53036057-ebf8bb80-349c-11e9-834d-1e7c03ee86e7.gif)

**Comment by richa208** [comment]
The feature to have 'save' and 'cancel' button is already present in the code but due to some bug these buttons are not visible.

**Comment by neozenweb** [comment]
This is the same issue I had faced with the Comments Add button too. On
Chrome dev tools (Ctrl Shift I) you can see the buttons if you switch to
other media like iphone or ipad etc. The problem is with the
"Responsiveness" of the web pages, just what I have observed.

**Comment by WickedBrat** [comment]
Thanks, for filing this issue as it wasn't visible to us on your build.
 @neozenweb @richa208 whosoever wishes to fix this may assign themselves on the issue and start working

**Comment by neozenweb** [comment]
@richa208 , Did you get this bug on Safari browser? I am not able to see it either in my local build or the development build. 
@WickedBrat How are the browser, media variations taken care of for the project?  Tried to check this bug on iphone (the netlify version, for safari browser), but the top black bar with hamburger menu on the left keeps disappearing.
