### ISSUE TITLE
Add dialog for confirmation to delete

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#153]
To delete an idea we must have dialog that prompts us to confirm before deleteing an idea from the user profile page.

This requires completion of three tasks:

- [ ] Removing the delete icon from the idea feed.

- [ ] Adding delete button on the profile page.

- [ ] Adding dialog to prompt for deleting an idea.

_You may create different PRs for the tasks_

**Comment by neozenweb** [comment]
I can take this up. But I do see that in my local build, the first part is already done. That is, "Delete" button is removed from idea feed in my local version, but it still shows on the development version. @WickedBrat can you confirm.

**Comment by WickedBrat** [comment]
@neozenweb please update your master branch with upstream and you'll be
able to see the changes.

**Comment by neozenweb** [comment]
Thanks @WickedBrat . I have located the code where to make changes, but before I proceed, take a look at these screenshots. In **idea-feed.component.html** classes used are like  idea-card__body, idea-card__icon etc. but in the existing **details.component.html** , the project-card related class components are being used for ideas too. Should I be changing this similar to idea-card components too.  
![image](https://user-images.githubusercontent.com/37545009/53094669-cbeee980-34e8-11e9-9d53-626af8e4372b.png)

![image](https://user-images.githubusercontent.com/37545009/53094685-d7daab80-34e8-11e9-9b39-764b8d402618.png)

**Comment by neozenweb** [comment]
@WickedBrat I have completed the first two parts and tested. Can I create a PR for the first two parts and a separate one for the dialog prompt part? 
Should the same kind of dialog be used, as is being used in expand view of the idea? Thanks.

**Comment by WickedBrat** [comment]
Yes @neozenweb, you can look at the [Angular Material Dialog](https://material.angular.io/components/dialog/overview) fir more details of implementation
