### ISSUE TITLE
Make the username-idea pair unique

### ISSUE THREAD

**Issue by RavicharanN** [Cynthesize/cynthesize-frontend#159]
Currently, one particular user can create any number of ideas with the same name. This has to be avoided so as to uniquely identify the ideas submitted by a particular user.  

This is a beginner friendly issue and shouldn't be too hard to resolve.

**Comment by WickedBrat** [comment]
@RavicharanN I'm unable to reproduce this bug. Please use the development build [cynthesize-develop.netlify.com](https://cynthesize-develop.netlify.com/add/idea) for checking

**Comment by WickedBrat** [comment]
Also FYI, the name column in the database is set to `unique` to avoid duplication in both idea and project tables.
