### ISSUE TITLE
Place the abstract of the project instead of the complete description alongside the project whereever it is displayed. 

### ISSUE THREAD

**Issue by RavicharanN** [Cynthesize/cynthesize-frontend#168]
Extension to #167 

Might just wanna show the abstract of the project here instead of the whole description. Would be better to put the abstract there (in the image below) and then a "See description" link at the bottom.
 
![screenshot 2019-02-23 at 5 21 29 pm](https://user-images.githubusercontent.com/22046387/53286123-ccf57480-378f-11e9-94af-cb5da41e9ceb.png)

**Comment by Jaggu-123** [comment]
@RavicharanN  I will like to do it .

**Comment by RavicharanN** [comment]
You can proceed. Keep us updated on the progress :) @Jaggu-123

**Comment by WickedBrat** [comment]
Completed
