### ISSUE TITLE
Changing font-family throughout the site

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#42]
We're using [Angular Material 2](https://material.angular.io) for most of the UI components. The `font-family` is set to Gotham Light for all the elements. But this doesn't get applied on most of the places. We want to use 1. Gotham Light for headings and prime texts and 2. Open Sans for all other texts throughout the site, may it be button text, paragraph or texts on any other Angular material component. 

Please take a look at [this fix](https://stackoverflow.com/questions/43747518/angular-material-and-changing-fonts)

**Comment by devgupta2607** [comment]
I don't really know angular. Can I give this a try?

**Comment by WickedBrat1** [comment]
Assigned to you @devgupta2607

**Comment by WickedBrat** [comment]
@devgupta2607 any updates??

**Comment by thenullterminator** [comment]
If not working Can I work on it

**Comment by WickedBrat** [comment]
@thenullterminator you can fix this :+1:
