### ISSUE TITLE
Change the /home route to idea-feed page.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#46]
### ER:
The /home should go to the route `http://localhost:4200/idea/feed`

### AR:
It is going to an empty home page.

### STR:
1. http://localhost:4200/home

### Screenshots:
![image](https://user-images.githubusercontent.com/28949397/51615509-0ac36b00-1f4e-11e9-9008-d5f347487c22.png)

**Comment by thesmallstar** [comment]
I will work on this 
 @sourabh1031 are you on it?

**Comment by sourabh1031** [comment]
@thesmallstar yes let me try if i am unable to do then you can take it up
