### ISSUE TITLE
Add a minimal loader to Idea Feed until ideas load

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#57]
**Please discuss the loader design that will be implemented.**

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by zerefwayne** [comment]
@thenullterminator You can work on this issue. Actually there's already a loader present in the site somewhere. Implement the same one.

**Comment by prijeshb** [comment]
loader is loading on top right corner 
Screenshot:
![screenshot 158](https://user-images.githubusercontent.com/16492616/52256216-e008e780-293b-11e9-828e-616ca75caf3d.png)
fixed it :
![screenshot 157](https://user-images.githubusercontent.com/16492616/52256261-0a5aa500-293c-11e9-91dd-1435780208f1.png)
![screenshot 156](https://user-images.githubusercontent.com/16492616/52256263-0c246880-293c-11e9-8a9a-3b32c142bf39.png)

**Comment by WickedBrat** [comment]
@prijeshb please create a PR for the fix for center spinner
