### ISSUE TITLE
Navbar URL fixes

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#59]
**These are the list of fixes that are required in the Navbar**

- [x] The idea button should link to `/idea/feed` as it does, it should have a plus icon that should link to `/idea/add` page.
- [x] The Project button should link `/project/feed`.

- [x] The Project button should have a plus icon that sould link to `/project/add`.

- [x] Remove `My Projects` and `About` section

- [ ] Add `"Add"` text aside the plus icon on the navbar.

**Comment by SuneetKumar19** [comment]
@opencodebot claim

**Comment by WickedBrat** [comment]
@thenullterminator and @SuneetKumar19 please fix the previous issues alloted to you before picking up new ones.

**Comment by sanyamdogra** [comment]
I want to work on this, can i?

**Comment by WickedBrat** [comment]
@sanyamdogra Most of the tasks has been completed. I've updated the issue, and you may start up with the task

**Comment by WickedBrat** [comment]
@sanyamdogra any updates?

**Comment by sanyamdogra** [comment]
I thought this has already been done that's why i worked on other one

**Comment by WickedBrat** [comment]
Yes, the specified was done. Now you need to add the text "Add" along with
the plus button in the header
