### ISSUE TITLE
Fix project stats

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#60]
In the project stats part, following fixes are required:

- [ ] Watching should display the length of array or should display 0 if the returned field is null.

- [ ] Delete `Mentors` and `Issues` part.

- [ ] Checkpoints should display `projectIssuessByprojectId.length`

**Comment by SuneetKumar19** [comment]
@opencodebot claim

**Comment by WickedBrat** [comment]
@SuneetKumar19 You may solve this issue.

**Comment by prijeshb** [comment]
> In the project stats part, following fixes are required:
> 
> * [x]  Watching should display the length of array or should display 0 if the returned field is null.
> * [x]  Delete `Mentors` and `Issues` part.
> * [x]  Checkpoints should display `projectIssuessByprojectId.length`

Made PR for it
