### ISSUE TITLE
Add social links to user profile

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#61]
At the users' profile page, add a dropdown to select the social platform and the URL to that platform. For example, the user wants to add github, facebook and twitter. The user would select from the dropdown which link to choose and in the corresponding text field, the user will add the link. The object that'll be sent as would be, 
```
	{
		"github": "https://github.com/Cynthesize",
		"facebook": "https://facebook.com/cynthesizetech",
		"twitter": "https://twitter.com/cynthesizetech"
	}
```
 This could be done in two parts:

- [ ] Create mutation for the request that'll be used.

- [ ] Implement dropdown and input field.

Dropdown to be used: [https://material.angular.io/components/select/overview](https://material.angular.io/components/select/overview)

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by WickedBrat** [comment]
@thenullterminator please fix the previous issues assigned to you. Later you can continue with these.

**Comment by punisher1151** [comment]
@WickedBrat Can I work on this

**Comment by WickedBrat** [comment]
Go ahead @punisher1151
