### ISSUE TITLE
Bug in add project form.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#66]
**Describe the bug**
A user can jump to second add-project form field even without filling previous ones.

**To Reproduce**
1. Go to 'http://localhost:4200/project/add'
2. Click on any stepper 1, 2, 3, 4

**Expected behavior**

A user shouldn't be able to go to the next form field if he hasn't filled the previous one.

**Additional context**
Try to disable the next steppers based on the length of form fields of previous one. Suggest some better solutions if you can.

Try reading about Angular Material Steppers for reference.

**Comment by thesmallstar** [comment]
@zerefwayne  Why cannot we directly use the linear stepper? Like the one mentioned in Angular docs, I tried doing it but the other options get permanently disabled. any ideas?

**Comment by zerefwayne** [comment]
@thesmallstar Go ahead.

**Comment by thesmallstar** [comment]
@zerefwayne  Why cannot we directly use the linear stepper? Like the one mentioned in Angular docs?
I tried that but it wont work,
