### ISSUE TITLE
Add watch-project button on project view page.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#67]
**Describe the solution you'd like**
Add buttons to watch a project beside and similar to the add Issue button.

Just adding a button for now will do the job. Functionality will be implemented later.

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
can I work on this

**Comment by WickedBrat** [comment]
@punisher1151 any updates?
