### ISSUE TITLE
Implement Popular and Latest sorting in Idea Feed.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/cynthesize-frontend#83]
The search filters are just plain text currently. Implement popular (sort by upvotes) and latest (sort by date descending) in idea feed.

![image](https://user-images.githubusercontent.com/28949397/52289909-f8592080-2994-11e9-8c05-44fbbdcde1d3.png)

**Comment by AdityaAnandKrishna** [comment]
@zerefwayne  can I work on this ?

**Comment by zerefwayne** [comment]
Go ahead. :+1:
