### ISSUE TITLE
Redirect upon idea submission

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#85]
Currently, when an idea is submitted, it doesn't redirect anywhere. It should redirect to ideas feed page uponn successful addition i.e. `/view/feed/ideas`.

**Comment by prijeshb** [comment]
Should I create PR for this?

**Comment by WickedBrat** [comment]
Yes @prijeshb, create PRs for the issue as soon as you complete it.

**Comment by WickedBrat** [comment]
completed in #97
