### ISSUE TITLE
Convert names to URLs

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#98]
The title of projects and ideas cards should be links to them. This needs to be changed on idea-feed page and profile page.

**Comment by thesmallstar** [comment]
I am working on it :)

**Comment by thesmallstar** [comment]
@WickedBrat Where should the idea page link? I can find the separate page for projects, but there is no such page for ideas. Am I missing something?

**Comment by WickedBrat** [comment]
@thesmallstar You're right about the project page. For the ideas, it should open the ideas model. Just as it does upon the click on the icon.

**Comment by thesmallstar** [comment]
@WickedBrat okay :)
